name: Keep Server Awake

on:
  schedule:
    - cron: '*/29 8-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: 'https://investifysg.herokuapp.com/healthz'
